apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
  argocd-image-updater.argoproj.io/image-list: nanajanashia/argocd-app:v1.x
  argocd-image-updater.argoproj.io/myapp-argo-application.update-strategy: semver
  argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitcreds
  argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/Sheril5/argocd-con.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
